### ISSUE TITLE
incorrect reduce

### ISSUE THREAD

**Issue by Snigur69** [belokonivan1707/Chisw.Project-3#10]
https://github.com/belokonivan1707/Chisw.Project-3/blob/917f89c828b600fca1f9f8cb5697d2ff5d7fd590/index.js#L77
You have to read a documentation about reduce method. The point is: when we call callback at the first time, if we have initialValue, then accumulator equal to initalValue and currentValue equal to first element of array. If we have not initialValue, then accumulator equal to first element of array and currentValue equal to the secont element of array.

**Comment by funny-how** [comment]
I overwrote the method
